"""Packaging rpms support for Fedora kernel builds."""
from __future__ import annotations

from kernelpatching.constants import PACKAGE_NAME
from kernelpatching.errors import Error
from kernelpatching.packaging.spec import adapt_rpm_spec
from kernelpatching.storage.files import sha256
from kernelpatching.storage.manifests import build_target
from kernelpatching.storage.manifests import validate_target
from kernelpatching.system.process import logged
from kernelpatching.system.process import run
from pathlib import Path
import difflib
import platform


def build_packages(tree: Path, directory: Path, make: list[str], release: str) -> list[dict]:
    spec = tree / "scripts/package/kernel.spec"
    original = spec.read_text(encoding="utf-8")
    adapted = adapt_rpm_spec(original)
    spec.write_text(adapted, encoding="utf-8")
    (directory / "packaging.diff").write_text("".join(difflib.unified_diff(
        original.splitlines(True), adapted.splitlines(True),
        fromfile="upstream/kernel.spec", tofile="local/kernel.spec")), encoding="utf-8")
    # Keep build-time debug information for BTF; omit separate large debug RPMs.
    # Upstream may also build a headers package; exclude it from installation.
    logged([*make, "binrpm-pkg", "INSTALL_MOD_STRIP=1", "RPMOPTS=--without debuginfo --with devel"],
           tree, directory / "build.log")
    packages = []
    for path in sorted(tree.glob("rpmbuild/RPMS/**/*.rpm")):
        info = run(["rpm", "-qp", "--qf", "%{NAME}|%{ARCH}|%{VERSION}|%{RELEASE}", path]).stdout.strip()
        name, arch, version, rpm_release = info.split("|")
        if name not in {PACKAGE_NAME, PACKAGE_NAME + "-devel"}:
            continue
        if arch != platform.machine():
            raise Error(f"Unexpected RPM architecture: {path}")
        packages.append({"name": name, "path": str(path.relative_to(directory)),
                         "sha256": sha256(path), "architecture": arch,
                         "nevra": f"{name}-{version}-{rpm_release}.{arch}"})
    if sorted(p["name"] for p in packages) != [PACKAGE_NAME, PACKAGE_NAME + "-devel"]:
        raise Error("The expected kernel and development RPM pair was not produced.")
    validate_packages(directory, {"schema": 2, "target": build_target(),
                                  "kernel_release": release, "packages": packages})
    return packages



def validate_packages(directory: Path, manifest: dict) -> list[Path]:
    validate_target(manifest)
    release = manifest["kernel_release"]
    if len(release) > 64:
        raise Error("The manifest does not contain a kernel release generated by this application.")
    packages = manifest["packages"]
    names = ["kernel", "kernel-devel"] if manifest.get("schema", 1) == 1 else [PACKAGE_NAME, PACKAGE_NAME + "-devel"]
    if sorted(p["name"] for p in packages) != names:
        raise Error("The manifest must contain exactly " + " and ".join(names) + ".")
    paths = []
    for package in packages:
        path = (directory / package["path"]).resolve()
        if not path.is_relative_to(directory.resolve()) or not path.is_file():
            raise Error("The RPM path escapes the build directory or the file is missing.")
        if sha256(path) != package["sha256"]:
            raise Error(f"The RPM has changed since it was built: {path}")
        result = run(["rpm", "-qp", "--qf", "%{NAME}|%{ARCH}|%{VERSION}|%{RELEASE}", path])
        name, arch, version, rpm_release = result.stdout.strip().split("|")
        if (name != package["name"] or arch != platform.machine()
                or f"{name}-{version}-{rpm_release}.{arch}" != package["nevra"]):
            raise Error(f"RPM metadata does not match the manifest: {path}")
        provides = run(["rpm", "-qp", "--provides", path]).stdout.splitlines()
        expected = f"{'kernel-devel' if name.endswith('-devel') else 'kernel'}-uname-r = {release}"
        if expected not in provides or "installonlypkg(kernel)" not in provides:
            raise Error(f"Required RPM Provides are missing: {path}")
        paths.append(path)
    return paths
